import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import Header from 'components/Header'
import Navbar from 'components/Navbar'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>{`Sutiwat's Portfolio`}</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
      </Head>
      <main className='relative min-h-screen w-screen bg-slate-500 pt-[70px]'>
        {/* <Header /> */}
        <Navbar />
        {/** About */}
        {/** Experience */}
        {/** Contact */}
      </main>
      <div className='h-screen bg-orange-300'></div>
    </>
  )
}
